Edited content in land.md
ACCESS-Hive/access-hive.github.io pull request #349
Opened 2023-06-27 06:26 UTC by heidinett

Minor changes made to written text in lang configuration (land.md).
Perhaps include an example of how CABLE is used (instead of the commented out text in the JULES section)?
Good to have feedback from Claire.

Fixes https://github.com/ACCESS-Hive/access-hive.github.io/issues/336

2023-06-28 00:17 UTC, ccarouge requested changes
I am not sure what you mean by "an example of how CABLE is used". What sort of details are you after?

2023-06-28 00:17 UTC, ccarouge commented on docs/models/model_components/land.md
> +Community Atmosphere Biosphere Land Exchange (CABLE)](cable-web) is a land surface model, used to calculate the fluxes of momentum, energy, water and carbon between the land surface and the atmospher
Since there is a separate page about biogeochemistry, would the following work better?
```suggestion
[Community Atmosphere Biosphere Land Exchange (CABLE)][cable-web] is a land surface model, used to calculate the fluxes of momentum, energy, water and carbon between the land surface and the atmosphere. It also models the main biogeochemical cycles of the land ecosystem when used in conjunction with [the CASA-CNP module][casa-cnp]. 
```

2023-06-28 00:17 UTC, ccarouge commented on docs/models/model_components/land.md
> +[um-web]: https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model
I would move all the links to the bottom. I find it easier to find them rather than at the end of a section.

2023-06-28 00:17 UTC, ccarouge commented on docs/models/model_components/land.md
> +[cable-web]: https://www.cawcr.gov.au/research/cable/
```suggestion
[cable-web]: https://www.cawcr.gov.au/research/cable/
[casa-cnp]: ../bgc_land/index.md#casa-cnp
```

2023-06-28 06:53 UTC, heidinett commented on docs/models/model_components/land.md
> +Community Atmosphere Biosphere Land Exchange (CABLE)](cable-web) is a land surface model, used to calculate the fluxes of momentum, energy, water and carbon between the land surface and the atmospher
As for an example, there was an existing example of how Jules is used, which I commented out:
<---!The Bureau of Meteorology (BoM) uses the JULES land surface scheme in its numerical weather prediction models such as ACCESS S (Seasonal) and C (City).--->
I thought it would be better to include a CABLE example rather than JULES.

2023-06-28 06:53 UTC, heidinett commented on docs/models/model_components/land.md
> +[um-web]: https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model
I agree with moving links to the bottom.

2023-06-30 04:50 UTC, KAUR1984 commented
Waiting to be reviewed. To be closed then

2023-07-04 03:53 UTC, merged