Adding FAQ to User Support
ACCESS-Hive/access-hive.github.io pull request #529
Opened 2023-08-14 03:44 UTC by svenbuder

- renaming "Get Support!" button to "FAQ / Get Support!" on homepage
- add FAQs and answers on the About / User Support page.

2023-08-14 05:45 UTC, atteggiani requested changes

2023-08-14 05:45 UTC, atteggiani commented on docs/about/user_support.md
I really like the page and the FAQ cards!!

A few minor comments:
> On this page we answer frequently asked questions, but also give additional information for support...

I would use "On this page we answer frequently asked questions, **and** also give additional information for support...
<br>

> How do model runs and model evaluation work together?

I would change the "runs" to "experiments" (also to be consistent with the image).

> or more practically speaking _model runs_, ...

Same thing, I would use "_model experiments_"...
<br>

> "What is the difference between **TEAMS** and **WORKING GROUPS**?"
Throughout this documentation, we are using the term **teams** to describe the teams of ACCESS-NRI.
By contrast, we refer to **working groups** as the groups of the ACCESS community that work on specific ACCESS components, configurations or research. These are formed by the scientific community itself and ACCESS-NRI liasises with them.

I am not sure if this Q/A is needed (as I don't recall we ever talk about **teams** in the website). 
If we do mention it, then I would keep it as:

"Throughout this documentation, we use the term **teams** to describe ACCESS-NRI's internal employees.
By contrast, we refer to **working groups** as the groups of the ACCESS community that work on specific ACCESS components, configurations or research topics. These working groups are formed by the scientific community itself, with ACCESS-NRI being the liaison between them.

2023-08-15 01:56 UTC, aidanheerdegen approved these changes
Just a typo, then I think it is fine to merge.

2023-08-15 01:56 UTC, aidanheerdegen commented on docs/about/user_support.md
> +    The perturbation experiment is run in the same was as the control, each successive run using the state (restarts) from the previous run. The perturbation experiment can then be compared with the
```suggestion
    The perturbation experiment is run in the same way as the control, each successive run using the state (restarts) from the previous run. The perturbation experiment can then be compared with the control experiment to see the effect of the perturbation.
```

2023-08-15 02:57 UTC, atteggiani requested changes
Added my Review in a more clear way! (Thanks @aidanheerdegen!)

2023-08-15 02:57 UTC, atteggiani commented on docs/about/user_support.md
> +On this page we answer frequently asked questions, but also give additional information for support, in case your question is not yet answered.
```suggestion
On this page we answer frequently asked questions (FAQs), and also give additional information for support, in case your question is not yet answered.
```

2023-08-15 02:57 UTC, atteggiani commented on docs/about/user_support.md
> +    Climate science - like all science - is based on the comparison of different models and hypothesis with observational data. We provide or support the frameworks to perform such comparisons as par
```suggestion
??? abstract "How do model experiments and model evaluation work together?"

    Climate science - like all science - is based on the comparison of different models and hypothesis with observational data. We provide or support the frameworks to perform such comparisons as part of the **model evaluation**. The different model hypotheses, or more practically speaking *model experiments*, are created by executing different model configurations with different setups; for example by perturbing initial conditions or by adding new physical prescriptions to the models.
```

2023-08-15 02:57 UTC, atteggiani commented on docs/about/user_support.md
> +    By contrast, we refer to **working groups** as the groups of the ACCESS community that work on specific ACCESS components, configurations or research. These are formed by the scientific community
I am not sure if this Q/A is needed (as I don't recall we ever talk about teams in the website).
If we do mention it, then I would keep it as:

```suggestion
Throughout this documentation, we use the term **teams** to describe ACCESS-NRI's internal employees.

By contrast, we refer to **working groups** as the groups of the ACCESS community that work on specific ACCESS components, configurations or research topics. These working groups are formed by the scientific community itself, with ACCESS-NRI liaising between them.
```

2023-08-15 03:39 UTC, atteggiani approved these changes

2023-08-25 02:06 UTC, atteggiani commented
Merging after discussing in sprint meeting.

2023-08-25 02:06 UTC, merged