EDITS: Minor edits made to content in run-access-cm.md
ACCESS-Hive/access-hive.github.io pull request #588
Opened 2023-09-26 06:14 UTC by heidinett

Made some minor edits to ARE/Gadi workflow in run-access-cm.md

Fixes Issue #587

2023-09-27 00:24 UTC, atteggiani requested changes

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +    If you are new to ACCESS-CM, we <b>recommend</b> that you follow the <b>ARE/<i>Gadi</i></b> workflow, as the <i>accessdev</i> workflow will soon be discontinued.
```suggestion
    If you are new to ACCESS-CM, we <b>strongly recommend</b> that you follow the <b>ARE/<i>Gadi</i></b> workflow, as the <i>accessdev</i> workflow will soon be discontinued.
```

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +    The workflow to run ACCESS-CM is currently in transition from <i>accessdev</i> to ARE/<i>Gadi</i>.
```suggestion
    The workflow to run {{ model }} is currently in transition from <i>accessdev</i> to ARE/<i>Gadi</i>.
```

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +    If you are new to ACCESS-CM, we <b>recommend</b> that you follow the <b>ARE/<i>Gadi</i></b> workflow, as the <i>accessdev</i> workflow will soon be discontinued.
```suggestion
    If you are new to {{ model }}, we <b>recommend</b> that you follow the <b>ARE/<i>Gadi</i></b> workflow, as the <i>accessdev</i> workflow will soon be discontinued.
```

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +                An {{ model }} simulation can be unique and input data can originate from various sources. Hence, if your simulation requires data originating from projects other than <code>access</c
```suggestion
                Every {{ model }} simulation can be unique and input data can originate from various sources. Hence, if your simulation requires data stored in project folders other than <code>access</code>, <code>hh5</code>, <code>hr22</code> or <code>ki32</code>, you need to add those projects to the storage path.
```

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +                For example, if your {{ model }} simulation requires data from <code>/g/data/tm70</code> and <code>/scratch/w40</code>, your full storage path will be: <code>gdata/access+gdata/hh5+gd
```suggestion
                For example, if your {{ model }} simulation requires data stored in <code>/g/data/tm70</code> and <code>/scratch/w40</code>, your full storage path will be: <code>gdata/access+gdata/hh5+gdata/hr22+gdata/ki32<b>+/gdata/tm70+scratch/w40</b></code>
```

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +        Now, launch an ARE session and, once it starts, click on <i>Launch VDI Desktop</i>.
```suggestion
        Launch the ARE session and, once it starts, click on <i>Launch VDI Desktop</i>.
```

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +            Your chosen workflow is ARE/<i>Gadi</i>. If you would prefer to run {{ model }} on <i>accessdev</i>, then select the <a href="#accessdev"><i>accessdev</i> workflow</a>.
```suggestion
            Your chosen workflow is ARE / <i>Gadi</i>. If you would prefer to run {{ model }} on <i>accessdev</i>, then select the <a href="#accessdev"><i>accessdev</i> workflow</a>.
```

I think leaving space makes it more readabale. Similarly to what is done in other similar parts of the page.

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +            If you have not yet setup your <i>accessdev</i> connection through `ssh`, please check the <a href="https://accessdev.nci.org.au/trac/wiki/GettingConnected">Getting Connected to Accessdev
```suggestion
            If you have not yet set up your <i>accessdev</i> connection through `ssh`, please check the <a href="https://accessdev.nci.org.au/trac/wiki/GettingConnected">Getting Connected to Accessdev</i></a> guide.
```

I think the verb is **set up**, not to be confused with the noun/adjective **setup** (ref. --> https://www.future-perfect.co.uk/grammar-tips/easy-mistakes/is-it-setup-set-up-or-set-up).

2023-09-27 00:24 UTC, atteggiani commented on docs/models/run-a-model/run-access-cm.md
> +                        <i>Local copy</i>
```suggestion
                        <i>Local-only copy</i>
```
I think it needs to be stressed that is only a local copy.

2023-09-27 07:28 UTC, heidinett commented on docs/models/run-a-model/run-access-cm.md
> +            If you have not yet setup your <i>accessdev</i> connection through `ssh`, please check the <a href="https://accessdev.nci.org.au/trac/wiki/GettingConnected">Getting Connected to Accessdev
ARE/Gadi was suggested for consistentcy with other uses of this term on the page. But, I am fine with your suggestion.

2023-10-04 04:28 UTC, atteggiani approved these changes

2023-10-04 04:28 UTC, merged